Repository flow-hydraulics/flow-wallet-api, pull requests merged in 2022-01, with the labels that each got.

#248 Fixed get account non-fungible token details response
  openapi.yml
Labels: documentation

#249 Fixed token setup error handling
  tests/tokens_service_test.go
  tokens/service.go
Labels: bug

#256 Dockerized e2e test suite
  .dockerignore
  Makefile
  README.md
  chain_events/listener.go
  docker-compose.dev.yml
  docker-compose.test-suite.yml
  docker/flow-cli/Dockerfile
  docker/wallet/Dockerfile
  tests/test/config.go
Labels: enhancement
